# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d498ccb872fcab5baa3db70b8f6ed404586d9a83a9083a82bb56b7523d2c29e0091e5fbdac486aae4be1f4d09ae0129ce1c4154ee2c44af1f93214dfc9b2f8d9

test:
  secret_key_base: 4aec2533dfb4227e482eb920d4f98abca842fae3bed9889a87780d8ecd3ebe18e673a319118479942018f5a320698f072665728a1c4c631f18823101cbc132ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
